### PR TITLE
Containerize the web app

### PR DESCRIPTION
**Pull request by eecavanna**
### Branch

Here's a link to the branch, where you can see the rendered `README.md` file:
- https://github.com/microbiomedata/nmdc-edge/tree/12-dockerize-the-web-app

### Summary of changes

1. I **containerized** the web app.
    1. `webapp-node16.Dockerfile`: Specification for container image using Node v16 (EOL).
    1. `webapp-node18.Dockerfile`: Specification for container image using Node v18.
    1. `docker-compose.yml`: Specification for container stack for local development; including the web app, MongoDB, and Cromwell.
    1. `README.md`: Instructions for instantiating the container-based development environment, and building and publishing container images for production use.
    image
3. I overhauled the **configuration** of the web app.
    1. Instead of multiple code files accessing environment variables directly via `process.env` (where whose values are either unvalidated strings or `undefined`, and don't receive any code completion by IDEs), the client and server now each have a single interface to their environment: a `config` object.
        1. `webapp/client/src/config.js` and `webapp/server/config.js`: These files create the `config` objects that provide the rest of the client and server code, respectively, with access to either (a) values derived from environment variables or (b) fallback values. Also serves as a catalog of supported environment variables, including their documentation.
        1. `webapp/client/.env.example` and `webapp/server/.env.example`: Example environment configuration files for client and server, respectively.
    1. I updated all references to environment variables throughout the codebase, to use the new `config` objects.
    1. I edited the existing `installation/install.sh` script accordingly.
4. I simplified **configuration** of PM2.
    1. `pm2.config.js`: Takes the place of the configuration file that used to be generated from the `installation/server_pm2.tmpl` template. The latter had an unnecessary dependency on an absolute file path, whereas PM2 supports the use of relative paths. Also, using JavaScript instead of JSON allowed for the inclusion of documentation.
    1. I edited the existing `installation/install.sh` script accordingly.
5. I converted some string concatenation-based **path construction** into standard `path.join()` operations.
   ```diff
   - const filePath = baseDir + "/" + subDir + "/file";
   + const filePath = path.join(baseDir, subDir, "file");
   ```

### Caution
1. I **did** rename some environment variables and may have also changed what the code base "expects" them to contain. This code is not a "drop-in replacement" for any existing deployments. I can guide the system administrator(s) through updating the environment variables accordingly.

### CODE REVIEW

**Comment by eecavanna** [comment]
I will use Node v18 or newer, given that Node v16 is [EOL](https://github.com/microbiomedata/nmdc-edge/issues/20).

**Comment by ssarrafan** [comment]
@eecavanna 
removing this so I can close the previous sprint, adding backlog label
please add to current sprint if you're planning to work on it

**Comment by eecavanna** [comment]
Still to do:
- [ ] Move documentation from within the `Dockerfile` to the `README.md` file
- [ ] File issues related to the development environment limitations

**Comment by eecavanna** [comment]
Hi @mflynn-lanl and @yxu-lanl, here's the branch where I containerized the application to facilitate deploying the application to the cloud. Given the changes involved, I don't expect you to review/merge this without my involvement (although you can if you want). I will talk with @mflynn-lanl about it at our next squad meeting.

**Pull request merged**
