### PR TITLE
Create a `README.md` file for the repository

### PR DESCRIPTION
**Pull request by eecavanna**
Here's a link to the "rendered" `README.md` file this branch contains: [Link](https://github.com/microbiomedata/nmdc-edge/blob/11-create-a-readmemd-file-that-contains-an-overview-of-the-repository/README.md).

I'll wait until the draft PR https://github.com/microbiomedata/nmdc-edge/pull/17 has been finished and merged, before populating the "Development" section. That PR is still under construction.

### CODE REVIEW

**Comment by eecavanna** [comment]
Hi @mflynn-lanl and @yxu-lanl, do you think you'll have time to review/merge this during the current sprint? If not, I'll move it to the next sprint.

**Comment by ssarrafan** [comment]
I'll move this to the next sprint for @mflynn-lanl to review.

**Comment by ssarrafan** [comment]
@mflynn-lanl  @yxu-lanl has this been reviewed yet?

**Review by yxu-lanl — APPROVED** [review]
@eecavanna Thanks for adding this file.

**Pull request merged**
